[2023-06-30T14:51:48.540+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: search_posts.update_db manual__2023-06-30T14:48:55.678506+00:00 [queued]>
[2023-06-30T14:51:48.563+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: search_posts.update_db manual__2023-06-30T14:48:55.678506+00:00 [queued]>
[2023-06-30T14:51:48.565+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-30T14:51:48.593+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): update_db> on 2023-06-30 14:48:55.678506+00:00
[2023-06-30T14:51:48.604+0000] {standard_task_runner.py:57} INFO - Started process 17286 to run task
[2023-06-30T14:51:48.617+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'search_posts', 'update_db', 'manual__2023-06-30T14:48:55.678506+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/search_posts.py', '--cfg-path', '/tmp/tmp050dp9wf']
[2023-06-30T14:51:48.622+0000] {standard_task_runner.py:85} INFO - Job 148: Subtask update_db
[2023-06-30T14:51:48.717+0000] {task_command.py:410} INFO - Running <TaskInstance: search_posts.update_db manual__2023-06-30T14:48:55.678506+00:00 [running]> on host 414be138234a
[2023-06-30T14:51:48.904+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='search_posts' AIRFLOW_CTX_TASK_ID='update_db' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T14:48:55.678506+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T14:48:55.678506+00:00'
[2023-06-30T14:51:49.096+0000] {warnings.py:110} WARNING - /opt/***/dags/search_posts.py:62: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  update_data['created'] = pd.to_datetime(update_data['created'] )

[2023-06-30T14:51:49.098+0000] {logging_mixin.py:149} INFO - 
    fresh_data.shape: (4180, 16)
    old_data.shape: (5848, 1)
    update_data.shape: (1356, 16)
    
[2023-06-30T14:51:49.136+0000] {logging_mixin.py:149} INFO -                       created   created_utc  ... search_term                topic
18  2023-06-29 23:08:05-05:00  1.688098e+09  ...     alcohol  alcoholic_beverages
93  2023-06-29 20:42:17-05:00  1.688089e+09  ...     alcohol  alcoholic_beverages
94  2023-06-29 13:54:37-05:00  1.688065e+09  ...     alcohol  alcoholic_beverages
118 2023-06-30 02:22:17-05:00  1.688110e+09  ...     alcohol  alcoholic_beverages
134 2023-06-29 23:00:45-05:00  1.688098e+09  ...     alcohol  alcoholic_beverages

[5 rows x 16 columns]
[2023-06-30T14:51:49.153+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/search_posts.py", line 74, in update_db
    raw_reddit_pulls['created'] = raw_reddit_pulls['created'].to_datetime64()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'to_datetime64'
[2023-06-30T14:51:49.175+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=search_posts, task_id=update_db, execution_date=20230630T144855, start_date=20230630T145148, end_date=20230630T145149
[2023-06-30T14:51:49.224+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 148 for task update_db ('Series' object has no attribute 'to_datetime64'; 17286)
[2023-06-30T14:51:49.311+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-30T14:51:49.357+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
