[2023-07-07T02:38:05.630+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/update_post_exposure.py
[2023-07-07T02:38:06.222+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/update_post_exposure.py for tasks to queue
[2023-07-07T02:38:09.908+0000] {logging_mixin.py:149} INFO - [2023-07-07T02:38:09.548+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/update_post_exposure.py
[2023-07-07T02:38:13.745+0000] {processor.py:836} INFO - DAG(s) dict_keys(['update_post_exposure']) retrieved from /opt/airflow/dags/update_post_exposure.py
[2023-07-07T02:38:18.730+0000] {logging_mixin.py:149} INFO - [2023-07-07T02:38:18.700+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-07T02:38:21.124+0000] {logging_mixin.py:149} INFO - [2023-07-07T02:38:21.122+0000] {dag.py:3490} INFO - Setting next_dagrun for update_post_exposure to 2023-07-06T00:00:00+00:00, run_after=2023-07-07T00:00:00+00:00
[2023-07-07T02:38:21.876+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_post_exposure.py took 18.988 seconds
[2023-07-07T02:46:44.769+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/update_post_exposure.py
[2023-07-07T02:46:47.182+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/update_post_exposure.py for tasks to queue
[2023-07-07T02:47:35.321+0000] {logging_mixin.py:149} INFO - [2023-07-07T02:47:33.889+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/update_post_exposure.py
[2023-07-07T02:52:21.456+0000] {logging_mixin.py:149} INFO - [2023-07-07T02:51:18.441+0000] {timeout.py:68} ERROR - Process timed out, PID: 185
[2023-07-07T02:52:44.732+0000] {logging_mixin.py:149} INFO - [2023-07-07T02:52:21.513+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/update_post_exposure.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader = importlib.machinery.SourceFileLoader(mod_name, filepath)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/update_post_exposure.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.6.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.6.2/best-practices.html#reducing-dag-complexity, PID: 185
[2023-07-07T02:52:47.362+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/update_post_exposure.py
