[2023-07-10T15:21:29.280+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.choose_best_model scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-10T15:21:29.431+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.choose_best_model scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-10T15:21:29.433+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T15:21:29.720+0000] {taskinstance.py:1327} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2023-07-09 00:00:00+00:00
[2023-07-10T15:21:29.823+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2023-07-10T15:21:29.891+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'choose_best_model', 'scheduled__2023-07-09T00:00:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpozutg312']
[2023-07-10T15:21:29.905+0000] {standard_task_runner.py:85} INFO - Job 253: Subtask choose_best_model
[2023-07-10T15:21:30.402+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.choose_best_model scheduled__2023-07-09T00:00:00+00:00 [running]> on host 414be138234a
[2023-07-10T15:21:31.432+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-09T00:00:00+00:00'
[2023-07-10T15:21:31.542+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 215, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_dag.py", line 34, in _choose_best_model
    best_accuracy = max(accuracies)
ValueError: max() arg is an empty sequence
[2023-07-10T15:21:31.665+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=my_dag, task_id=choose_best_model, execution_date=20230709T000000, start_date=20230710T152129, end_date=20230710T152131
[2023-07-10T15:21:31.955+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 253 for task choose_best_model (max() arg is an empty sequence; 75)
[2023-07-10T15:21:32.044+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T15:21:32.228+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
