[2023-06-27T02:03:42.109+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: search_posts.update_db manual__2023-06-27T02:03:05.515097+00:00 [queued]>
[2023-06-27T02:03:42.129+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: search_posts.update_db manual__2023-06-27T02:03:05.515097+00:00 [queued]>
[2023-06-27T02:03:42.130+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T02:03:42.159+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): update_db> on 2023-06-27 02:03:05.515097+00:00
[2023-06-27T02:03:42.170+0000] {standard_task_runner.py:57} INFO - Started process 522 to run task
[2023-06-27T02:03:42.184+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'search_posts', 'update_db', 'manual__2023-06-27T02:03:05.515097+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/search_posts.py', '--cfg-path', '/tmp/tmp_orqaqwa']
[2023-06-27T02:03:42.190+0000] {standard_task_runner.py:85} INFO - Job 76: Subtask update_db
[2023-06-27T02:03:42.300+0000] {task_command.py:410} INFO - Running <TaskInstance: search_posts.update_db manual__2023-06-27T02:03:05.515097+00:00 [running]> on host 414be138234a
[2023-06-27T02:03:42.481+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='search_posts' AIRFLOW_CTX_TASK_ID='update_db' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T02:03:05.515097+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-27T02:03:05.515097+00:00'
[2023-06-27T02:03:42.488+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/search_posts.py", line 58, in update_db
    fresh_data = ti.xcom_pull(task_id = "get_posts")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2023-06-27T02:03:42.509+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=search_posts, task_id=update_db, execution_date=20230627T020305, start_date=20230627T020342, end_date=20230627T020342
[2023-06-27T02:03:42.564+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 76 for task update_db (xcom_pull() got an unexpected keyword argument 'task_id'; 522)
[2023-06-27T02:03:42.650+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-27T02:03:42.855+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
