[2023-06-27T01:48:38.986+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: search_posts.get_posts manual__2023-06-27T01:48:29.004480+00:00 [queued]>
[2023-06-27T01:48:39.004+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: search_posts.get_posts manual__2023-06-27T01:48:29.004480+00:00 [queued]>
[2023-06-27T01:48:39.006+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T01:48:39.037+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_posts> on 2023-06-27 01:48:29.004480+00:00
[2023-06-27T01:48:39.047+0000] {standard_task_runner.py:57} INFO - Started process 258 to run task
[2023-06-27T01:48:39.060+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'search_posts', 'get_posts', 'manual__2023-06-27T01:48:29.004480+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/search_posts.py', '--cfg-path', '/tmp/tmp997n4t24']
[2023-06-27T01:48:39.065+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask get_posts
[2023-06-27T01:48:39.216+0000] {task_command.py:410} INFO - Running <TaskInstance: search_posts.get_posts manual__2023-06-27T01:48:29.004480+00:00 [running]> on host 414be138234a
[2023-06-27T01:48:39.375+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='search_posts' AIRFLOW_CTX_TASK_ID='get_posts' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T01:48:29.004480+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-27T01:48:29.004480+00:00'
[2023-06-27T01:48:40.530+0000] {logging_mixin.py:149} INFO - <Response [200]>
[2023-06-27T01:48:40.543+0000] {logging_mixin.py:149} INFO - searching tests...
[2023-06-27T01:48:54.238+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/search_posts.py", line 36, in get_posts
    raw_reddit_posts = pd.concat([results_df, df])
NameError: name 'results_df' is not defined
[2023-06-27T01:48:54.271+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=search_posts, task_id=get_posts, execution_date=20230627T014829, start_date=20230627T014838, end_date=20230627T014854
[2023-06-27T01:48:54.304+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 71 for task get_posts (name 'results_df' is not defined; 258)
[2023-06-27T01:48:54.367+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-27T01:48:54.408+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
